# Generated by Django 3.2.4 on 2024-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('CP', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='registroProblemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=100)),
                ('ProblemaC', models.CharField(max_length=100)),
            ],
        ),
    ]
